name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'
  schedule:
    - cron: '0 16 * * *'

env:
  GMP_VERSION: "6.3.0"
  MPFR_VERSION: "4.2.1"
  ISL_VERSION: "0.26"
  MPC_VERSION: "1.3.1"
  CLONE_DIR: "${{ github.workspace }}/git_clone"
  GITHUB_USER: "${{ secrets.USERNAME }}"
  GITHUB_EMAIL: "${{ secrets.EMAIL }}"
  GITHUB_TOKEN: "${{ secrets.API_TOKEN_GITHUB }}"
  HOME: "${{ github.workspace }}"
  SOURCE_DIR: "${{ github.workspace }}/source"
  OUTPUT_DIR: "${{ github.workspace }}/output"
  BUILD_DIR: "${{ github.workspace }}/build"
  WGET_DIR: "${{ github.workspace }}/wget"
  MPREFIX: "${{ github.workspace }}/output/toolchain"
  MSYSROOT: "${{ github.workspace }}/output/sysroot"
  PATH: "${{ github.workspace }}/output/toolchain/bin:/usr/bin:/bin"
  CFLAGS: "-g0 -O2"
  CXXFLAGS: "-g0 -O2"
  LDFLAGS: "-g0 -O2 -Wl,-O2,--hash-style=both"

jobs:
  make-headers:
    name: make-${{ matrix.select }}-headers
    runs-on: ubuntu-latest
    outputs:
      ${{ matrix.select }}-output1: ${{ steps.${{ matrix.select }}-hash.outputs.test }}
    env:
      SELECT: "${{ matrix.select }}"
    strategy:
      fail-fast: false
      matrix:
        select:
          - linux
          - musl
    steps:
    - name: Clone ${{ matrix.select }}
      run: |
        if [ "${SELECT}" = "linux" ]; then
          git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux ${SOURCE_DIR}/${SELECT} -b master --depth=1
        elif [ "${SELECT}" = "musl" ]; then
          git clone git://git.musl-libc.org/musl ${SOURCE_DIR}/${SELECT} -b master --depth=1
        fi
    - name: Set hash value into environment variables
      id: ${{ matrix.select }}-hash
      run: |
        cd ${SOURCE_DIR}/${SELECT}

        echo "HASH=$(git log -1 --format='%H')" >> ${GITHUB_ENV}
    - name: Cache ${{ matrix.select }} headers
      uses: actions/cache@v3
      id: headers-cache
      with:
        path: ${{ env.MSYSROOT }}/usr/include
        key: ${{ env.SELECT }}-${{ env.HASH }}
    - name: Skip build
      if: ${{ steps.headers-cache.outputs.cache-hit == 'true' }}
      run: exit 0
    - name: Install tools
      if: ${{ steps.headers-cache.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      if: ${{ steps.headers-cache.outputs.cache-hit != 'true' }}
      run: mkdir -vp ${SOURCE_DIR} ${OUTPUT_DIR} ${MSYSROOT}/usr/include
    - name: Make ${{ matrix.select }} headers
      if: ${{ steps.headers-cache.outputs.cache-hit != 'true' }}
      run: |
        cd ${SOURCE_DIR}/${SELECT}
        if [ "${SELECT}" = "linux" ]; then
          make ARCH=arm64 mrproper -j$(nproc --all)
          make O="${OUTPUT_DIR}/linux" ARCH=arm64 INSTALL_HDR_PATH="${MSYSROOT}/usr" headers_install -j$(nproc --all)
        elif [ "${SELECT}" = "musl" ]; then
          make ARCH="aarch64" prefix="/usr" DESTDIR="${MSYSROOT}" install-headers -j$(nproc --all)
        fi

  build-gmp:
    runs-on: ubuntu-latest
    steps:
    - name: Cache gmp
      uses: actions/cache@v3
      id: gmp-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/gmp
        key: gmp-${{ env.GMP_VERSION }}
    - name: Skip build
      if: ${{ steps.gmp-cache.outputs.cache-hit == 'true' }}
      run: exit 0
    - name: Install tools
      if: ${{ steps.gmp-cache.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      if: ${{ steps.gmp-cache.outputs.cache-hit != 'true' }}
      run: mkdir -vp ${SOURCE_DIR} ${OUTPUT_DIR} ${WGET_DIR} ${BUILD_DIR}/build-gmp
    - name: Wget and unzip gmp-${{ env.GMP_VERSION }}
      if: ${{ steps.gmp-cache.outputs.cache-hit != 'true' }}
      run: |
        wget -P ${WGET_DIR} https://ftp.gnu.org/gnu/gmp/gmp-${GMP_VERSION}.tar.xz
        tar -xJvf ${WGET_DIR}/gmp-${GMP_VERSION}.tar.xz -C ${SOURCE_DIR}
    - name: Make gmp
      if: ${{ steps.gmp-cache.outputs.cache-hit != 'true' }}
      run: |
        cd ${BUILD_DIR}/build-gmp
        ${SOURCE_DIR}/gmp-${GMP_VERSION}/configure --prefix="${OUTPUT_DIR}/gmp"
        make all -j$(nproc --all)
        make install -j$(nproc --all)

  build-isl:
    needs: [ build-gmp ]
    runs-on: ubuntu-latest
    steps:
    - name: Cache isl
      uses: actions/cache@v3
      id: isl-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/isl
        key: isl-${{ env.ISL_VERSION }}-gmp${{ env.GMP_VERSION }}
    - name: Skip build
      if: ${{ steps.isl-cache.outputs.cache-hit == 'true' }}
      run: exit 0
    - name: Cache gmp
      if: ${{ steps.isl-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache@v3
      id: gmp-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/gmp
        key: gmp-${{ env.GMP_VERSION }}
    - name: Install tools
      if: ${{ steps.isl-cache.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      if: ${{ steps.isl-cache.outputs.cache-hit != 'true' }}
      run: mkdir -vp ${SOURCE_DIR} ${OUTPUT_DIR}/gmp ${WGET_DIR} ${BUILD_DIR}/build-isl
    - name: Wget and unzip isl-${{ env.ISL_VERSION }}
      if: ${{ steps.isl-cache.outputs.cache-hit != 'true' }}
      run: |
        wget -P ${WGET_DIR} https://libisl.sourceforge.io/isl-${ISL_VERSION}.tar.gz
        tar -xzvf ${WGET_DIR}/isl-${ISL_VERSION}.tar.gz -C ${SOURCE_DIR}
    - name: Make isl
      if: ${{ steps.isl-cache.outputs.cache-hit != 'true' }}
      run: |
        cd ${BUILD_DIR}/build-isl
        ${SOURCE_DIR}/isl-${ISL_VERSION}/configure --prefix="${OUTPUT_DIR}/isl" --with-gmp="${OUTPUT_DIR}/gmp"
        make all -j$(nproc --all)
        make install -j$(nproc --all)

  build-mpfr:
    needs: [ build-gmp ]
    runs-on: ubuntu-latest
    steps:
    - name: Cache mpfr
      uses: actions/cache@v3
      id: mpfr-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/mpfr
        key: mpfr-${{ env.MPFR_VERSION }}-gmp${{ env.GMP_VERSION }}
    - name: Skip build
      if: ${{ steps.mpfr-cache.outputs.cache-hit == 'true' }}
      run: exit 0
    - name: Cache gmp
      if: ${{ steps.mpfr-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache@v3
      id: gmp-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/gmp
        key: gmp-${{ env.GMP_VERSION }}
    - name: Install tools
      if: ${{ steps.mpfr-cache.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      if: ${{ steps.mpfr-cache.outputs.cache-hit != 'true' }}
      run: mkdir -vp ${SOURCE_DIR} ${OUTPUT_DIR}/gmp ${WGET_DIR} ${BUILD_DIR}/build-mpfr
    - name: Wget and unzip mpfr-${{ env.MPFR_VERSION }}
      if: ${{ steps.mpfr-cache.outputs.cache-hit != 'true' }}
      run: |
        wget -P ${WGET_DIR} https://ftp.gnu.org/gnu/mpfr/mpfr-${MPFR_VERSION}.tar.gz
        tar -xzvf ${WGET_DIR}/mpfr-${MPFR_VERSION}.tar.gz -C ${SOURCE_DIR}
    - name: Make mpfr
      if: ${{ steps.mpfr-cache.outputs.cache-hit != 'true' }}
      run: |
        cd ${BUILD_DIR}/build-mpfr
        ${SOURCE_DIR}/mpfr-${MPFR_VERSION}/configure --prefix="${OUTPUT_DIR}/mpfr" --with-gmp="${OUTPUT_DIR}/gmp"
        make all -j$(nproc --all)
        make install -j$(nproc --all)

  build-mpc:
    needs: [ build-gmp, build-mpfr ]
    runs-on: ubuntu-latest
    steps:
    - name: Cache mpc
      uses: actions/cache@v3
      id: mpc-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/mpc
        key: mpc-${{ env.MPC_VERSION }}-gmp${{ env.GMP_VERSION }}-mpfr${{ env.MPFR_VERSION }}
    - name: Skip build
      if: ${{ steps.mpc-cache.outputs.cache-hit == 'true' }}
      run: exit 0
    - name: Cache gmp
      if: ${{ steps.mpc-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache@v3
      id: gmp-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/gmp
        key: gmp-${{ env.GMP_VERSION }}
    - name: Cache mpfr
      if: ${{ steps.mpc-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache@v3
      id: mpfr-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/mpfr
        key: mpfr-${{ env.MPFR_VERSION }}-gmp${{ env.GMP_VERSION }}
    - name: Install tools
      if: ${{ steps.mpc-cache.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      if: ${{ steps.mpc-cache.outputs.cache-hit != 'true' }}
      run: mkdir -vp ${SOURCE_DIR} ${OUTPUT_DIR}/{gmp,mpfr} ${WGET_DIR} ${BUILD_DIR}/build-mpc
    - name: Wget and unzip mpc-${{ env.MPC_VERSION }}
      if: ${{ steps.mpc-cache.outputs.cache-hit != 'true' }}
      run: |
        wget -P ${WGET_DIR} https://ftp.gnu.org/gnu/mpc/mpc-${MPC_VERSION}.tar.gz
        tar -xzvf ${WGET_DIR}/mpc-${MPC_VERSION}.tar.gz -C ${SOURCE_DIR}
    - name: Make mpc
      if: ${{ steps.mpc-cache.outputs.cache-hit != 'true' }}
      run: |
        cd ${BUILD_DIR}/build-mpc
        ${SOURCE_DIR}/mpc-${MPC_VERSION}/configure --prefix="${OUTPUT_DIR}/mpc" --with-gmp="${OUTPUT_DIR}/gmp" --with-mpfr="${OUTPUT_DIR}/mpfr"
        make all -j$(nproc --all)
        make install -j$(nproc --all)

  build-gcc-and-push:
    needs: [ make-headers, build-mpc, build-isl ]
    runs-on: ubuntu-latest
    steps:
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      run: mkdir -vp ${SOURCE_DIR} ${OUTPUT_DIR}/{gmp,mpfr,mpc,isl} ${MPREFIX} ${MSYSROOT}/usr/include ${BUILD_DIR}/{build-binutils,build-gcc,build-musl}
    - name: Cache gmp
      uses: actions/cache@v3
      id: gmp-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/gmp
        key: gmp-${{ env.GMP_VERSION }}
    - name: Cache mpfr
      uses: actions/cache@v3
      id: mpfr-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/mpfr
        key: mpfr-${{ env.MPFR_VERSION }}-gmp${{ env.GMP_VERSION }}
    - name: Cache isl
      uses: actions/cache@v3
      id: isl-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/isl
        key: isl-${{ env.ISL_VERSION }}-gmp${{ env.GMP_VERSION }}
    - name: Cache mpc
      uses: actions/cache@v3
      id: mpc-cache
      with:
        path: ${{ env.OUTPUT_DIR }}/mpc
        key: mpc-${{ env.MPC_VERSION }}-gmp${{ env.GMP_VERSION }}-mpfr${{ env.MPFR_VERSION }}
    - name: Cache musl headers
      uses: actions/cache@v3
      id: musl-cache
      with:
        path: ${{ env.MSYSROOT }}/usr/include
        key: musl-${{ env.musl_hash }}
    - name: Cache linux headers
      uses: actions/cache@v3
      id: linux-cache
      with:
        path: ${{ env.MSYSROOT }}/usr/include
        key: linux-${{ env.linux_hash }}
    - name: Clone binutils
      run: git clone git://sourceware.org/git/binutils-gdb ${SOURCE_DIR}/binutils -b master --depth=1
    - name: Clone gcc
      run: git clone git://gcc.gnu.org/git/gcc ${SOURCE_DIR}/gcc -b master --depth=1
    - name: Clone musl
      run: git clone git://git.musl-libc.org/musl ${SOURCE_DIR}/musl -b master --depth=1
    - name: Configure binutils
      run: |
        cd ${BUILD_DIR}/build-binutils
        ${SOURCE_DIR}/binutils/configure --target="aarch64-linux-musl" --prefix="${MPREFIX}" --with-sysroot="${MSYSROOT}" --disable-multilib --disable-werro --with-gmp="${OUTPUT_DIR}/gmp" --with-mpc="${OUTPUT_DIR}/mpc" --with-mpfr="${OUTPUT_DIR}/mpfr" --with-isl="${OUTPUT_DIR}/isl"
    - name: Make binutils
      run: |
        cd ${BUILD_DIR}/build-binutils
        make all-binutils all-gas all-ld -j$(nproc --all)
        make install-strip-binutils install-strip-gas install-strip-ld -j$(nproc --all)
    - name: Configure gcc
      run: |
        cd ${BUILD_DIR}/build-gcc
        ${SOURCE_DIR}/gcc/configure --target="aarch64-linux-musl" --prefix="${MPREFIX}" --with-sysroot="${MSYSROOT}" --enable-languages="c,c++" --disable-multilib --disable-bootstrap --disable-libsanitizer --disable-werror --enable-initfini-array --with-arch=armv8-a --with-abi=lp64 --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419 --with-gmp="${OUTPUT_DIR}/gmp" --with-mpc="${OUTPUT_DIR}/mpc" --with-mpfr="${OUTPUT_DIR}/mpfr" --with-isl="${OUTPUT_DIR}/isl"
    - name: Make gcc (compiler)
      run: |
        cd ${BUILD_DIR}/build-gcc
        make all-gcc -j$(nproc --all)
        make install-strip-gcc -j$(nproc --all)
    - name: Make gcc (libgcc-static)
      run: |
        cd ${BUILD_DIR}/build-gcc
        make enable_shared=no all-target-libgcc -j$(nproc --all)
        make install-strip-target-libgcc -j$(nproc --all)
    - name: Configure musl
      run: |
        cd ${BUILD_DIR}/build-musl
        LIBCC_DIR=$(find ${MPREFIX}/lib/gcc/aarch64-linux-musl -maxdepth 1 -type d -name "[0-9]*")
        ARCH="aarch64"
        CC="aarch64-linux-musl-gcc"
        CROSS_COMPILE="aarch64-linux-musl-"
        LIBCC="${LIBCC_DIR}/libgcc.a"
        ${SOURCE_DIR}/musl/configure --host="aarch64-linux-musl" --prefix="/usr"
    - name: Make musl
      run: |
        cd ${BUILD_DIR}/build-musl
        make AR="aarch64-linux-musl-ar" RANLIB="aarch64-linux-musl-ranlib" -j$(nproc --all)
        make AR="aarch64-linux-musl-ar" RANLIB="aarch64-linux-musl-ranlib" DESTDIR="${MSYSROOT}" install -j$(nproc --all)
        rm -vf ${MSYSROOT}/lib/ld-musl-aarch64.so.1
        cp -avf ${MSYSROOT}/usr/lib/libc.so ${MSYSROOT}/lib/ld-musl-aarch64.so.1
    - name: Make gcc (libgcc-shared)
      run: |
        cd ${BUILD_DIR}/build-gcc
        make -C aarch64-linux-musl/libgcc distclean -j$(nproc --all)
        make enable_shared=yes all-target-libgcc -j$(nproc --all)
        make install-strip-target-libgcc -j$(nproc --all)
    - name: Make gcc (libstdc++-v3)
      run: |
        cd ${BUILD_DIR}/build-gcc
        make all-target-libstdc++-v3 -j$(nproc --all)
        make install-strip-target-libstdc++-v3 -j$(nproc --all)
    - name: Make gcc (libgomp)
      run: |
        cd ${BUILD_DIR}/build-gcc
        make all-target-libgomp -j$(nproc --all)
        make install-strip-target-libgomp -j$(nproc --all)
    - name: Merge directory
      run: cp -avf ${MSYSROOT}/lib ${MSYSROOT}/usr/* ${MPREFIX}/aarch64-linux-musl
    - name: Push
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/chase535/aarch64-linux-musl-gcc ${CLONE_DIR} -b main --depth=1
        cd ${CLONE_DIR}
        OLD_FILES=`find . -maxdepth 1 -not \( -type d -name "." -o -type d -name ".git" -o -type d -name ".github" -o -type f -name "README.md" \)`
        [ -n "${OLD_FILES}" ] && git rm -rf ${OLD_FILES} && git commit -as -m "Delete old files"
        cp -avf ${MPREFIX}/* ${CLONE_DIR}
        git add . -f
        git commit -as -m "$(${CLONE_DIR}/bin/aarch64-linux-musl-gcc --version)"
        git push origin main -f
